# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SenDtV4MFCExX7tOwfPwADin-RWjmCrQ
"""

a = input()
b = a[::-1]
if a == b:
  print("palindrome")
else:
  print("invalid")

a = int(input())
fact = 1
for i in range(1,a+1):
  fact*=i
print("factorial:",fact)

a=int(input())
b=int(input())
print(max(a,b))

a = int(input())
t = a
b = len(str(t))
sum = 0
while t>0:
  d = t%10
  sum += d**b
  t = t//10
if (sum==a):
  print("armstrong")
else:
  print("invalid")

for n in range(1,51):
  if n>1:
    for i in range (2,n):
      if n%i==0:
        break
    else:
        print(n)

c = float(input())
f = (c*9/5)+32
print(f)

a = input()
b = input()
a,b = b,a
print(a)
print(b)

n = int(input())
a,b = 0,1
for i in range(n):
  print(a)
  a,b = b,a+b

a = int(input())
b = int(input())
c = int(input())
avg = (a+b+c)//3
print(avg)

a = int(input())
if a < 0:
  print("negative")
elif a > 0:
  print("positive")
else:
  print("zero")

a = int(input())
if a%4==0:
  print("leap year")
else:
  print("normal")

a = int(input())
if a%2==0:
  print("even")
else:
  print("odd")

a = input()
b = input()
if sorted(a)==sorted(b):
  print("anagram")
else:
  print("not")

for i in range(1,6):
  for j in range(1,i+1):
    print(j,end="")
  print()

a = int(input())
for i in range(a):
  print(" "*i+"*"*(a-i))

a = int(input())
for i in range(1,a+1):
  print(" "*(a-i)+"* "*i)
for i in range(a-1,0,-1):
  print(" "*(a-i)+"* "*i)

a = int(input())
for i in range(1,a+1):
  print(" "*(a-i)+"* "*i)

a=[10,20,80,40,50,60]
l = sorted(a,reverse = True)[:3]
print(l)

a = input()
b = input()
if (a==b,b==a):
  print("anagram")
else:
  print("not")

import math
a = int(input())
if math.sqrt(a):
  print("its power of 2")
else:
  print("not")

a = input()
b = input()
if len(a)!= len(b):
  print("not same len")
else:
  c = 0
for i in range(len(a)):
  if a[i]!=b[i]:
    c+=1
if c == 1:
  print("yes")
else:
  print("no")

a = input()
l = ""
for i in range(len(a)):
    c = ""
    for j in range(i, len(a)):
        if a[j] not in c:
            c += a[j]
        else:
            break
    if len(c) > len(l):
        l = c
print("Longest substring:", l)
print("Length:", len(l))

st = input()
st1 = list(st.lower())
vowels = ['a', 'e', 'i', 'o', 'u']
vlist = []
r = 0
for i in st1:
    if i in vowels:
        vlist.append(i)
vlist.reverse()
for i in range(len(st1)):
    if st1[i] in vowels:
        st1[i] = vlist[r]
        r += 1
print("".join(st1))

s = input()
longest = ""
for i in range(len(s)):
    for j in range(i + 1, len(s) + 1):
        sub = s[i:j]
        if sub == sub[::-1] and len(sub) > len(longest):
            longest = sub
print(longest)

a = int(input())
x = list(map(int,input().split()))
for i in range(1,a):
  if (x[i]==0):
    d = x[i-1]+1
    print(d)
    break

#class and object
class student:
  def __init__(self,name,age) :
    self.name = name
    self.age = age
  def display(self):
    print("name:",self.name)
    print("age:",self.age)
obj = student("hems",3)
obj.display()

#inheritance
class father:
  def bike(self):
    print("father has bike")
class son(father):
  def cycle(self):
    print("son has cycle")
obj = son()
obj.bike()

#polymorphism
class animal:
  def sound(self):
    print("animal makes sound")
class dog(animal):
  def sound(self):
    print("dog barks")
obj=dog()
obj.sound()

#abstraction
class bank:
  def __init__(self):
    self.balance=5000
  def show_balance(self):
    print("balance:",self.balance)
obj = bank()
obj.show_balance()

#polymorphism(overloading)
class multiply:
  def product(self,a=None,b=None,c=None):
    if a and b and c:
      print("product =",a*b*c)
    elif a and b:
      print("product =",a*b)
    else:
      print("invalid input")
obj = multiply()
obj.product(2,3)
obj.product(2,3,4)

n=int(input())
r = int(str(n)[::-1])
for i in range(2,r):
  if r%i==0:
    print("not prime")
    break
else:
    print("prime")

a = int(input())
b = a**2
c = int(str(a)[::-1])
d = c**2
e = int(str(b)[::-1])
if d == e:
  print("adam")
else:
  print("not")

def is_prime(n):
    if n < 2:
        return False
    for i in range(2, n):
        if n % i == 0:
            return False
    return True

def is_circular_prime(n):
    s = str(n)
    for i in range(len(s)):
        r = int(s[i:] + s[:i])  # rotation
        if not is_prime(r):
            return False
    return True

n = int(input("Enter number: "))

if is_circular_prime(n):
    print("Circular Prime")
else:
    print("Not Circular Prime")

import os
os.environ['KAGGLE_USERNAME'] = 'VISH'
os.environ['KAGGLE_KEY']='KGAT_77512d142a19dc2744801fd2f635a0ea'

!pip install kaggle

!kaggle datasets download -d 'yasserh/titanic-dataset'

!unzip titanic.zip

import pandas as pd
df = pd.read_csv("titanic-dataset.zip")
df.head(10)

df.tail(10)

print(len(df))
print(df.shape)

df.info()

df.describe()

df.duplicated().sum()

df.dtypes

df.columns

df.drop

df.isnull().sum()

df["Age"].fillna(df["Age"].median(),inplace=True)
print(df[["Age"]].head(10))
print(df[["Age"]].isnull().sum())