# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SenDtV4MFCExX7tOwfPwADin-RWjmCrQ
"""

a = input()
b = a[::-1]
if a == b:
  print("palindrome")
else:
  print("invalid")

a = int(input())
fact = 1
for i in range(1,a+1):
  fact*=i
print("factorial:",fact)

a=int(input())
b=int(input())
print(max(a,b))

a = int(input())
t = a
b = len(str(t))
sum = 0
while t>0:
  d = t%10
  sum += d**b
  t = t//10
if (sum==a):
  print("armstrong")
else:
  print("invalid")

for n in range(1,51):
  if n>1:
    for i in range (2,n):
      if n%i==0:
        break
    else:
        print(n)

c = float(input())
f = (c*9/5)+32
print(f)

a = input()
b = input()
a,b = b,a
print(a)
print(b)

n = int(input())
a,b = 0,1
for i in range(n):
  print(a)
  a,b = b,a+b

a = int(input())
b = int(input())
c = int(input())
avg = (a+b+c)//3
print(avg)

a = int(input())
if a < 0:
  print("negative")
elif a > 0:
  print("positive")
else:
  print("zero")

a = int(input())
if a%4==0:
  print("leap year")
else:
  print("normal")

a = int(input())
if a%2==0:
  print("even")
else:
  print("odd")

a = input()
b = input()
if sorted(a)==sorted(b):
  print("anagram")
else:
  print("not")

for i in range(1,6):
  for j in range(1,i+1):
    print(j,end="")
  print()

a = int(input())
for i in range(a):
  print(" "*i+"*"*(a-i))

a = int(input())
for i in range(1,a+1):
  print(" "*(a-i)+"* "*i)
for i in range(a-1,0,-1):
  print(" "*(a-i)+"* "*i)

a = int(input())
for i in range(1,a+1):
  print(" "*(a-i)+"* "*i)

a=[10,20,80,40,50,60]
l = sorted(a,reverse = True)[:3]
print(l)

a = input()
b = input()
if (a==b,b==a):
  print("anagram")
else:
  print("not")

import math
a = int(input())
if math.sqrt(a):
  print("its power of 2")
else:
  print("not")

a = input()
b = input()
if len(a)!= len(b):
  print("not same len")
else:
  c = 0
for i in range(len(a)):
  if a[i]!=b[i]:
    c+=1
if c == 1:
  print("yes")
else:
  print("no")

a = input()
l = ""
for i in range(len(a)):
    c = ""
    for j in range(i, len(a)):
        if a[j] not in c:
            c += a[j]
        else:
            break
    if len(c) > len(l):
        l = c
print("Longest substring:", l)
print("Length:", len(l))

st = input()
st1 = list(st.lower())
vowels = ['a', 'e', 'i', 'o', 'u']
vlist = []
r = 0
for i in st1:
    if i in vowels:
        vlist.append(i)
vlist.reverse()
for i in range(len(st1)):
    if st1[i] in vowels:
        st1[i] = vlist[r]
        r += 1
print("".join(st1))

s = input()
longest = ""
for i in range(len(s)):
    for j in range(i + 1, len(s) + 1):
        sub = s[i:j]
        if sub == sub[::-1] and len(sub) > len(longest):
            longest = sub
print(longest)

a = int(input())
x = list(map(int,input().split()))
for i in range(1,a):
  if (x[i]==0):
    d = x[i-1]+1
    print(d)
    break

#class and object
class student:
  def __init__(self,name,age) :
    self.name = name
    self.age = age
  def display(self):
    print("name:",self.name)
    print("age:",self.age)
obj = student("hems",3)
obj.display()

#inheritance
class father:
  def bike(self):
    print("father has bike")
class son(father):
  def cycle(self):
    print("son has cycle")
obj = son()
obj.bike()

#polymorphism
class animal:
  def sound(self):
    print("animal makes sound")
class dog(animal):
  def sound(self):
    print("dog barks")
obj=dog()
obj.sound()

#abstraction
class bank:
  def __init__(self):
    self.balance=5000
  def show_balance(self):
    print("balance:",self.balance)
obj = bank()
obj.show_balance()

#polymorphism(overloading)
class multiply:
  def product(self,a=None,b=None,c=None):
    if a and b and c:
      print("product =",a*b*c)
    elif a and b:
      print("product =",a*b)
    else:
      print("invalid input")
obj = multiply()
obj.product(2,3)
obj.product(2,3,4)

n=int(input())
r = int(str(n)[::-1])
for i in range(2,r):
  if r%i==0:
    print("not prime")
    break
else:
    print("prime")

a = int(input())
b = a**2
c = int(str(a)[::-1])
d = c**2
e = int(str(b)[::-1])
if d == e:
  print("adam")
else:
  print("not")

def is_prime(n):
    if n < 2:
        return False
    for i in range(2, n):
        if n % i == 0:
            return False
    return True

def is_circular_prime(n):
    s = str(n)
    for i in range(len(s)):
        r = int(s[i:] + s[:i])  # rotation
        if not is_prime(r):
            return False
    return True

n = int(input("Enter number: "))

if is_circular_prime(n):
    print("Circular Prime")
else:
    print("Not Circular Prime")



import os
os.environ['KAGGLE_USERNAME'] = 'VISH'
os.environ['KAGGLE_KEY']='KGAT_77512d142a19dc2744801fd2f635a0ea'

!pip install kaggle

!kaggle datasets download -d 'yasserh/titanic-dataset'

!unzip titanic.zip

import pandas as pd
df = pd.read_csv("titanic-dataset.zip")
df.head(10)

df.tail(10)

print(len(df))
print(df.shape)

df.info()

df.describe()

df.duplicated().sum()

df.dtypes

df.columns

df.drop

df.isnull().sum()

df["Age"].fillna(df["Age"].median(),inplace=True)
print(df[["Age"]].head(10))
print(df[["Age"]].isnull().sum())



class Student:
    def __init__(self, name, marks):
        self.name = name
        self.marks = marks

    def total(self):
        return sum(self.marks)

    def average(self):
        return sum(self.marks) / len(self.marks)

    def highest_mark(self):
        return max(self.marks)

    def status(self):
        return "Pass" if all(mark >= 35 for mark in self.marks) else "Fail"


s = Student("Ravi", [78, 45, 92, 30, 67])

print("Total:", s.total())
print("Average:", s.average())
print("Highest Mark:", s.highest_mark())
print("Status:", s.status())

class Employee:
    def __init__(self, name, scores):
        self.name = name
        self.scores = scores

    def best_score(self):
        return max(self.scores)

    def average_score(self):
        return sum(self.scores) / len(self.scores)

    def months_above_80(self):
        return len([x for x in self.scores if x > 80])


e = Employee("Priya", [75, 82, 90, 65, 88, 70])

print("Best Score:", e.best_score())
print("Average Score:", round(e.average_score(), 1))
print("Months Above 80:", e.months_above_80())

class ParkingLot:
    def __init__(self, vehicles):
        self.vehicles = vehicles

    def check_vehicle(self, number):
        return number in self.vehicles

    def duplicates(self):
        dup = []
        for v in self.vehicles:
            if self.vehicles.count(v) > 1 and v not in dup:
                dup.append(v)
        return dup

    def unique_count(self):
        return len(set(self.vehicles))


p = ParkingLot([101, 105, 110, 101, 115, 105])

print("Duplicate Vehicles:", p.duplicates())
print("Unique Vehicles:", p.unique_count())

class Player:
    def __init__(self, name, scores):
        self.name = name
        self.scores = scores

    def highest_score(self):
        return max(self.scores)

    def lowest_score(self):
        return min(self.scores)

    def average_score(self):
        return sum(self.scores) / len(self.scores)

    def half_centuries(self):
        return len([x for x in self.scores if x >= 50])


p = Player("Virat", [45, 102, 78, 35, 61])

print("Highest Score:", p.highest_score())
print("Lowest Score:", p.lowest_score())
print("Average Score:", round(p.average_score(), 1))
print("Half Centuries:", p.half_centuries())

class ShoppingCart:
    def __init__(self, prices):
        self.prices = prices

    def total_bill(self):
        return sum(self.prices)

    def costliest_item(self):
        return max(self.prices)

    def discounted_bill(self):
        total = self.total_bill()
        if total > 5000:
            total *= 0.85
        return total


cart = ShoppingCart([1200, 3500, 800, 1500])

print("Total Bill:", cart.total_bill())
print("Costliest Item:", cart.costliest_item())
print("Discounted Bill:", cart.discounted_bill())

class Patient:
    def __init__(self, name, temps):
        self.name = name
        self.temps = temps

    def highest_temp(self):
        return max(self.temps)

    def lowest_temp(self):
        return min(self.temps)

    def abnormal_count(self):
        return len([t for t in self.temps if t > 100])


p = Patient("Kumar", [98.4, 99.1, 101.2, 102.3, 98.9])

print("Highest Temperature:", p.highest_temp())
print("Lowest Temperature:", p.lowest_temp())
print("Abnormal Readings:", p.abnormal_count())

class MovieTicket:
    def __init__(self, booked):
        self.booked = booked

    def is_booked(self, seat):
        return seat in self.booked

    def total_booked(self):
        return len(self.booked)

    def available_seats(self):
        return [i for i in range(1, 21) if i not in self.booked]


m = MovieTicket([1, 3, 5, 7, 10, 15])

print("Total Booked Seats:", m.total_booked())
print("Available Seats:", m.available_seats())

class Student:
    def __init__(self, attendance):
        self.attendance = attendance

    def highest_attendance(self):
        return max(self.attendance)

    def lowest_attendance(self):
        return min(self.attendance)

    def eligible_students(self):
        return len([a for a in self.attendance if a >= 75])


s = Student([85, 70, 92, 65, 78, 88])

print("Highest Attendance:", s.highest_attendance())
print("Lowest Attendance:", s.lowest_attendance())
print("Eligible Students:", s.eligible_students())
